### ISSUE TITLE
Question about configuring search query parameters

### ISSUE THREAD

**Issue by MemeRunner** [twitter/twurl#102]
My goal is to pull the top tweet with #voicefirst in the tweet, from the previous day’s tweets.

### Expected behavior

Ideally, I'd like to get the search results according to the following conditions:

**1. Only tweets with #voicefirst in tweet, not user description**

Currently it's including tweets with #voicefirst in the user description

**Only want the following parameters, instead of the full data set I’ve been getting.**
-- created_at
-- id
-- name
-- screen_name
-- text
-- retweet_count
-- Favorite_count

**Want only results for the previous day, or the previous 24 hour period.**
I’ve been trying various queries using max_id, since_id, count or until, but when I add the dates, it’s only giving me the summary of results that fit the query. 

### Actual behavior

I’ve set up the following query.

twurl h ‘/1.1/search/tweets.json?q=%23voicefirst&result_type=popular’ | jq .

It’s returning what I presume is the top tweet for the current day.

I've tried various queries, but when I add the date parameters, it's only returning a summary of the results, like this example.

/1.1/search/tweets.json?q=%23voicefirst%20since%3A2018-09-18%20until%3A2018-09-19&src=typd

### Steps to reproduce the behavior

Here are some fo the search queries I've tried.
/1.1/search/tweets.json?q=%23voicefirst&result_type=popular

/1.1/search/tweets.json?q=%23voicefirst%20since%3A2018-09-18%20until%3A2018-09-19&src=typd

/1.1/search/tweets.json?q=%23voicefirst&result_type=popular+until%3A2018-09-19
 - That returned a large number of results, which I tried to curtail with a count of 3 in the next query

/1.1/search/tweets.json?q=%23voicefirst&result_type=popular+until%3A2018-09-19&count%3A3
 - Produced a count of all the results that matched the query.

**Comment by andypiper** [comment]
You've got three questions here, none of which appear to be issues with `twurl` itself, but do depend on the Twitter [standard search API](https://developer.twitter.com/en/docs/tweets/search/overview/standard.html).

1. Only tweets with #voicefirst in tweet, not user description

You'd have to do this filtering yourself - the API matches against both text of the status, and any Twitter bio descriptions.

2. Only want the following parameters, instead of the full data set I’ve been getting.

You can achieve this using `jq` and filtering down to the desired values. Here's how I would do that. You can find more examples at https://t.co/recipes

```
jq '[.statuses[] | {created_at: .created_at, id: .id_str, name: .user.name, screen_name: .user.screen_name, text: .text, retweet_count: .retweet_count, favorite_count: .favorite_count}]'
```

3. Want only results for the previous day, or the previous 24 hour period.

Your queries are not quite built correctly. The second example is probably closest to what you want. You cannot use the "popular" parameter with the since and until query operators, unfortunately.

Here's what I came up with to solve questions 2 and 3:

```
twurl "/1.1/search/tweets.json?q=%23voicefirst%20since:2018-09-22%20until:2018-09-23&count=3" | jq '[.statuses[] | {created_at: .created_at, id: .id_str, name: .user.name, screen_name: .user.screen_name, text: .text, retweet_count: .retweet_count, favorite_count: .favorite_count}]'
```

Note that the premium 30-day search (there's a free sandbox option) would be an even better way of doing this, as it has more powerful query operators and a more complete Tweet index. Unfortunately, `twurl` does not currently work with that API, so I'd recommend using `curl` or `httpie` instead.
